title: Subordinación y Valor
description: Un universo distópico ambientado en la Argentina post-apocalíptica del año 2178
baseurl: "/universo-syv"
url: "https://kodexArg.github.io"

# Theme configuration
remote_theme: pages-themes/midnight@v0.2.0
# El tema midnight proporciona una estética más oscura y distópica

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/
  proyecto:
    output: true
    permalink: /:collection/:title/
  lore:
    output: true
    permalink: /:collection/:title/
  personajes:
    output: true
    permalink: /:collection/:title/
  historias:
    output: true
    permalink: /:collection/:title/
  rpg_manual_del_jugador:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_proyecto"
      type: "proyecto"
    values:
      layout: "post"
      category: "proyecto"
  - scope:
      path: "_lore"
      type: "lore"
    values:
      layout: "post"
      category: "lore"
  - scope:
      path: "_personajes"
      type: "personajes"
    values:
      layout: "post"
      category: "personajes"
  - scope:
      path: "_historias"
      type: "historias"
    values:
      layout: "post"
      category: "historias"
  - scope:
      path: "_rpg_manual_del_jugador"
      type: "rpg_manual_del_jugador"
    values:
      layout: "post"
      category: "rpg_manual_del_jugador"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .github 